### ISSUE TITLE
Improve Search Sorting

### ISSUE THREAD

**Issue by itohatweb** [denoland/dotland#2001] opened 2022-02-03 16:05 UTC
Currently when searching a module on `deno.land/x` most of the time you find what you need. But as soon as more modules get added the search ranking gets messed up.
In fact when searching for example `oak` it will not even show up on the page (https://deno.land/x?query=oak). Another example would be when searching `discord` popular repositories such as `discordeno` or `harmony` do not get listed and when searching them exactly then they show up on 4th place.

**Comment by crowlKats** [comment] 2022-02-03 16:06
Duplicate of https://github.com/denoland/deno_registry2/issues/69

**Closed by crowlKats** 2022-02-03 16:06 UTC
