### ISSUE TITLE
system status looks bad on mobile 

### ISSUE THREAD

**Issue by ry** [denoland/dotland#2330] opened 2022-07-29 00:01 UTC
![image](https://user-images.githubusercontent.com/80/181656506-3e4cee66-954a-45bc-9677-02d4522d7a91.png)

https://discord.com/channels/684898665143206084/826085979344470037/1002364612257263626

**Comment by kitsonk** [comment] 2022-07-29 00:10
Duplicate of #2323

**Closed by kitsonk** 2022-07-29 00:10 UTC
Labels: duplicate
