### ISSUE TITLE
fresh logo not visible in project readme on deno.land website

### ISSUE THREAD

**Issue by DivyamAhuja** [denoland/dotland#2242] opened 2022-07-06 08:35 UTC
fresh logo not visible in project readme on deno.land website cause of relative path of logo
![image](https://user-images.githubusercontent.com/39771050/177506899-1268350b-3fa1-4d00-bc73-f46adef1bfff.png)

**Comment by kidonng** [comment] 2022-07-09 04:52
Duplicate of #2041

**Closed** 2022-07-21 05:55 UTC
Labels: duplicate
