### ISSUE TITLE
Incorrect syntax rendering, visible in std's toml.ts

### ISSUE THREAD

**Issue by danopia** [denoland/dotland#1613] opened 2020-12-05 15:19 UTC
Here: https://deno.land/std@0.79.0/encoding/toml.ts#L276
![image](https://user-images.githubusercontent.com/40628/101246724-5ed83280-3715-11eb-8f44-5b292ddb686c.png)

Seems like the mixing of quotes is causing the syntax highlighter to enter a very long multiline string that doesn't actually exist.

Reporting here as per [Discord](https://discord.com/channels/684898665143206084/684898665151594506/784796935055867934)

**Comment by kt3k** [comment] 2021-01-01 13:59
This seems caused by the vendored version of Prism.js in react-prism-renderer repository
( https://github.com/FormidableLabs/prism-react-renderer/tree/master/src/vendor/prism ), and even when we replaced the vendored prism with the latest prism.js, it still has the problem in handling template-literal at near line 644 of toml.ts. ( You can check it in [prism.js playground](https://prismjs.com/test.html).)

On the other hand, hightlight.js seems handling toml.ts without any error. (Created codesandbox [demo](https://codesandbox.io/s/modern-frog-gvm54?file=/src/App.tsx) for it.)

How about switching to highlight.js for syntax highlighting? cc @lucacasonato

**Comment by danopia** [comment] 2021-01-03 17:58
The problem with latest prism.js is pretty wild, it depends on a couple different earlier lines in the file being present, including commented-out code. I've reported it here: https://github.com/PrismJS/prism/issues/2694

I like prism overall, but it's hard for me to complain about switching if highlight.js works better & doesn't break on other things

**Comment by danopia** [comment] 2021-02-05 05:37
The latest prismjs test page now renders this file correctly ^^ so should be cleared to upgrade the dependency

**Comment by crowlKats** [comment] 2022-07-19 06:33
Doesnt seem to be the case anymore after various prisma updates, so closing

**Closed by crowlKats** 2022-07-19 06:33 UTC
