### ISSUE TITLE
Can not close the modal in Safari 

### ISSUE THREAD

**Issue by weykon** [denoland/dotland#2338] opened 2022-08-01 08:01 UTC
![image](https://user-images.githubusercontent.com/36456814/182101358-062f6d66-0d28-4d58-baea-549a39f9dbf4.png)

Safari  (v14.1 )

**Comment by crowlKats** [comment] 2022-08-01 09:01
Duplicate of #2332

**Closed by crowlKats** 2022-08-01 09:01 UTC
