### ISSUE TITLE
[Feature Request]: Dark mode for the website

### ISSUE THREAD

**Issue by silvioprog** [denoland/dotland#2614] opened 2022-12-03 18:16 UTC
Hey team.

It would be nice to support dark mode for the [Deno website](https://deno.land/manual/introduction). Especially the documentation area, improving the text readability.

Cheers

**Comment by yakuppgeyikk96** [comment] 2022-12-22 08:35
What is the status of this feature? Is there anyone working on it?

**Comment by crowlKats** [comment] 2022-12-22 08:43
No one is working on this; its extremely low priority, it hasn't even been discussed if we actually want to do this.

**Comment by yakuppgeyikk96** [comment] 2022-12-22 10:17
Can I work on it for future consideration if you don't mind.

**Comment by crowlKats** [comment] 2022-12-23 12:55
Closing as duplicate of #409; will follow-up in that issue

**Closed by crowlKats** 2022-12-23 12:55 UTC
Labels: suggestion
