### ISSUE TITLE
ui bug with version numbers?

### ISSUE THREAD

**Issue by andykais** [denoland/dotland#2645] opened 2023-01-05 15:19 UTC
Hi, I have created a module https://deno.land/x/torm. It has two versions:
- https://deno.land/x/torm@1.0.1
- https://deno.land/x/torm@v1.0.0

because I goofed up the tags, the first has a `v` prefix, while the second does not. The site correctly redirects to the latest (`1.0.1`), but the versions on the side only show the first of the two
<img width="312" alt="Screen Shot 2023-01-05 at 10 18 33 AM" src="https://user-images.githubusercontent.com/6627147/210814747-4f4f98ab-28b2-4952-b537-7154446a8435.png">

**Comment by andykais** [comment] 2023-01-09 15:10
I am not sure if the actual ui bug was fixed, but I am no longer experiencing this after publishing a new version

**Comment by crowlKats** [comment] 2023-01-09 15:21
the problem is caching, so keeping this open

**Comment by crowlKats** [comment] 2023-06-01 01:06
Closing in favour of #2567, as it has the same underlying issue

**Closed by crowlKats** 2023-06-01 01:06 UTC
