### ISSUE TITLE
Curation of /x ?

### ISSUE THREAD

**Issue by reviewher** [denoland/dotland#2080] opened 2022-03-21 20:26 UTC
https://deno.land/x has third party modules.  Of the top 5 listed, only two actually work with `/x`.  In order:

Does not work: https://deno.land/x/lodash does not mention Deno at all, and [the maintainers are not interested in adding Deno examples](https://github.com/lodash/lodash/pull/4316#issuecomment-499176465)

Does not work: https://deno.land/x/dayjs does not mention Deno at all, and [the recommendation is to use `skypack`](https://github.com/iamkun/dayjs/issues/1382)

Works: https://deno.land/x/sheetjs README is not loading but [the README has Deno examples](https://github.com/SheetJS/sheetjs)

Does not work: https://deno.land/x/xstate does not mention Deno in the main README. 
 [There is a recipe that recommends `skypack`](https://github.com/statelyai/xstate/blob/main/docs/recipes/deno.md)

Works: https://deno.land/x/corejs README has a Deno example.

If `/x` is intended as a host, it does not make sense to highlight modules that do not actually use or recommend `/x`.

**Comment by crowlKats** [comment] 2022-03-21 20:35
> Works: https://deno.land/x/sheetjs README is not loading but [the README has Deno examples](https://github.com/SheetJS/sheetjs)

We have a max README filesize, and sheetjs is exceeding that.

The registry is not curated, and the main list goes by starcount.

**Comment by crowlKats** [comment] 2022-03-21 20:36
Duplicate of #548

**Closed by crowlKats** 2022-03-21 20:36 UTC

**Comment by kitsonk** [comment] 2022-03-21 22:25
@lucacasonato and I have talked about improving the "scoring" of packages based on a defined set of criteria. I realise there is no issue for that. I will open one, but to be clear, `deno.land/x` doesn't curate nor "recommend" packages.

**Comment by kitsonk** [comment] 2022-03-21 22:28
Ref #2801

**Comment by ayoreis** [comment] 2022-05-04 17:25
The reason they don't work is explained here: https://stackoverflow.com/a/69483910/16342352
