### ISSUE TITLE
Undo accidental tag of testing branch causing 'latest' version of 3rd party package to look updated

### ISSUE THREAD

**Issue by JamesBroadberry** [denoland/dotland#2512] opened 2022-09-28 20:39 UTC
Hi,

I'm the maintainer of https://deno.land/x/bcrypt and I've recently tagged a commit on a branch that no longer exists with the name "test".

It now looks like it's the latest version of the package.

How do I go about removing that?

Thanks,
James

**Comment by kitsonk** [comment] 2022-09-29 11:09
The registry is immutable by design. To update the latest version, you would need to publish a newer tag.

**Comment by JamesBroadberry** [comment] 2022-09-29 11:28
So because of an accidental tag pushed, I've got to release a new version with no changes made at all and still have this accidental push listed in the history, even though the source doesn't exist?

**Comment by kitsonk** [comment] 2022-09-29 11:58
Immutable does mean immutable.  When someone says "publish this tag" we copy the code into the registry and ensure it is available, so people can depend on ensuring the code will exist in the future.

The only reason we would remove code is if there is a legal requirement to do so.

**Comment by JamesBroadberry** [comment] 2022-09-29 12:08
Just created a new [release](https://github.com/JamesBroadberry/deno-bcrypt/releases/tag/v0.4.1) with nothing changed. Would be good if tagging branches other than the default/main branch didn't cause this kind of mess though.

**Comment by kitsonk** [comment] 2022-09-30 00:17
It is hard to predict what people mean.  Some people keep a branch seperate for a build of code specifically tailored to Deno.  So we presume nothing as any presumption would be wrong.  If someone sends a registry a message that they published a new tag, the registry takes their word for it.

This is un-actionable, so respectfully closing.

**Closed by kitsonk** 2022-09-30 00:17 UTC
