### ISSUE TITLE
Request: publish modules from Gitlab

### ISSUE THREAD

**Issue by ngdangtu-vn** [denoland/dotland#2399] opened 2022-08-22 03:03 UTC
refer https://github.com/denoland/wanted_modules/issues/57

Sorry for spamming, I just think it is really necessary for dev to have more option rather than Github. What if one day github become evil for being monopoly?

**Comment by crowlKats** [comment] 2022-08-22 03:05
Duplicate of denoland/deno_registry2#53

**Closed by crowlKats** 2022-08-22 03:05 UTC
