### ISSUE TITLE
0.189.0 version for deno_std packages are not suggesting the latest version

### ISSUE THREAD

**Issue by gm112** [denoland/dotland#2761] opened 2023-05-27 12:40 UTC
See - <https://deno.land/std@0.189.0/http/mod.ts> or <https://deno.land/std@0.189.0/dotenv/load.ts>. 

The true latest version as of the time of writing this issue should be `0.189.0`, but the documentation page is suggesting to go to the latest version, which redirects you to `0.177.1`. 

I'm not familiar with how dotland works, though if I were to take a guess, I believe this may be an issue with perhaps how the git tags are being queried from the repository?

I have not verified if this is affecting other packages - this is only behavior I've seen from the standard library package so far.

**Comment by crowlKats** [comment] 2023-05-27 12:41
Duplicate of https://github.com/denoland/deno_std/issues/3408

**Closed by crowlKats** 2023-05-27 12:41 UTC

**Comment by gm112** [comment] 2023-05-27 12:44
Oh, my apologies! I only searched open issues. I will say that, others will probably get confused and the only suggestion I can give is to perhaps add a button that says "Most Current Version", or something to differentiate a patch release from the latest current release.
