### ISSUE TITLE
"Go to Latest" button broken for some repos

### ISSUE THREAD

**Issue by JasperVanEsveld** [denoland/dotland#2384] opened 2022-08-16 17:17 UTC
Maybe I am missing something here
When loading this [module](https://deno.land/x/discordeno_audio_plugin) it correctly goes to the latest version (1.0.2).
However the "Go to Latest" button shows up and brings you back one version, where it again is visible and brings you back one more version.

![image](https://user-images.githubusercontent.com/9715316/184939079-70bd0718-0eaa-451a-8500-4eb653bf5728.png)
![image](https://user-images.githubusercontent.com/9715316/184939112-5231b5d9-a145-4ea7-a08e-d42a41efa2f8.png)
![image](https://user-images.githubusercontent.com/9715316/184939136-bc150d86-3853-4845-8918-9b5184f5bba5.png)

The dropdown also only shows the original version when on version 1.0.0
![image](https://user-images.githubusercontent.com/9715316/184939343-0c61b7b9-a75e-4ed0-a0e7-1f903e885f05.png)

**Comment by kitsonk** [comment] 2022-08-16 21:11
The link on the 1.0.2 page is pointing to version 1.0.1. It is likely some sort of caching problem going with our new infrastructure.

**Comment by kitsonk** [comment] 2022-08-17 00:59
The JSON from the service is wrong:

```json
{
	"upload_options": {
		"type": "github",
		"ref": "1.0.2",
		"repository": "JasperVanEsveld/discordeno-audio-plugin"
	},
	"versions": [
		"1.0.1",
		"1.0.0"
	],
	"kind": "module",
	"module": "discordeno_audio_plugin",
	"uploaded_at": "2022-08-16T17:08:00.350Z",
	"star_count": 1,
	"nav": [
		{
			"kind": "dir",
			"path": "/src"
		},
		{
			"kind": "dir",
			"path": "/utils"
		}
	],
	"version": "1.0.2",
	"docNodes": [],
	"path": "/mod.ts",
	"latest_version": "1.0.1",
	"description": "Enables audio to be played and received by a Discordeno bot"
}
```

But the module is "correct"...

```json
{
	"tags": [],
	"description": "Enables audio to be played and received by a Discordeno bot",
	"star_count": 1,
	"popularity_score": 5,
	"latest_version": "1.0.2",
	"versions": [
		"1.0.2",
		"1.0.1",
		"1.0.0"
	],
	"name": "discordeno_audio_plugin"
}
```

So it feels like it was a transient error when the module was published where the page got cached with an outdated version of the module.  Hrmmmm...

**Comment by kitsonk** [comment] 2022-08-17 01:18
I manually cleared down the cache in the datastore and it seems to have resolved the issue, though I am trying to isolate the initial root cause of "stale" data being committed to the datastore.

**Comment by kitsonk** [comment] 2022-08-17 05:55
Ok, there were a couple things that could have caused this, one being the in-memory cache not being invalidated across all instances of the API server.  The other being that when the publish webhook was processed, it wasn't deleting cached versions of pages located in the datstore.  Both of those have been fixed now. There maybe still be some stuff hanging out, and I will try to run a cleanup script later to identify any "bad" cached pages and delete them.

**Closed by kitsonk** 2022-08-17 05:55 UTC
Labels: bug
