### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by nhrones** [denoland/dotland#2733] opened 2023-03-27 17:53 UTC
When I click on any of the `Command` method links in the manual I only get 404 - Not Found errors?

**Comment by Creative-Difficulty** [comment] 2023-03-28 14:19
I cannot find these links. Please provide an example.

**Comment by nhrones** [comment] 2023-03-28 16:32
on this page:
`https://deno.land/api@v1.32.1?s=Command&p=prototype.output`

If you click on the link `output(): Promise<CommandOutput>`

you are sent to `https://deno.land/api@v1.32.1?s=Command&p=prototype.output`
which shows 404 - Not Found

Same with every method link on that page!

**Comment by nhrones** [comment] 2023-03-28 16:41
Same issue on this page.  Incorrect links
https://deno.land/api@v1.32.1?s=Deno.ChildProcess

**Comment by Creative-Difficulty** [comment] 2023-04-02 13:24
Duplicate of #2690

**Comment by andykais** [comment] 2023-04-02 18:53
Related, It seems that searching for "subprocess" yields a bunch of documentation pages that 404.
![screenshot(1176)](https://user-images.githubusercontent.com/6627147/229372800-c232cb50-f094-432f-808a-92bde3bc6b47.png)

For example, this one "Communicating with subprocesses" https://deno.land/manual@v1.32.3/permissions#subprocess-permissions 
![screenshot(1177)](https://user-images.githubusercontent.com/6627147/229372799-e3cbd7c7-d409-4eee-9678-69e7e4f98661.png)

I cant seem to find documentation on the `new Deno.Command(...)` interface, only the `Deno.run(...)` interface, which I believe is deprecated?

**Comment by crowlKats** [comment] 2023-04-04 13:35
@andykais the search has been fixed now. However, you are correct, there currently is no manual documentation for the new subprocess API, see https://github.com/denoland/manual/issues/597

**Closed** 2023-04-08 16:34 UTC
