### ISSUE TITLE
https://deno.land/add_module not working

### ISSUE THREAD

**Issue by AumyF** [denoland/dotland#2685] opened 2023-02-11 02:46 UTC
The form in https://deno.land/add_module is not accepting any inputs.
Developer tools says all .js files under deno.land is 500 Internal Server Error.

**Comment by crowlKats** [comment] 2023-02-11 03:04
The cause for this is #2683. I have promoted an older deployment as a hotfix for now.

**Comment by Thisisaarush** [comment] 2023-04-16 08:34
The following URL is working for me - https://deno.land/add_module
Is this a valid issue now?

![Screenshot 2023-04-16 140241](https://user-images.githubusercontent.com/37803437/232286840-d6568e8e-458d-4925-ba29-1e1802693f8d.png)

**Comment by kt3k** [comment] 2023-04-17 06:17
@Thisisaarush This is resolved in #2687

Note: We still have issue with upgrading Fresh of this project, but let's track that somewhere else.

**Closed by kt3k** 2023-04-17 06:17 UTC
