### ISSUE TITLE
Third party modules in /x/ missing releases starting a few days ago

### ISSUE THREAD

**Issue by SheetJSDev** [denoland/dotland#2072] opened 2022-03-18 22:45 UTC
https://deno.land/x/sheetjs v0.18.4 was tagged a few days ago (https://github.com/sheetjs/sheetjs/tree/v0.18.4) but the latest version showing on deno.land is v0.18.3 .  Trying to hit the url https://deno.land/x/sheetjs@v0.18.4 results in a 404

**Comment by GJZwiers** [comment] 2022-03-19 09:30
I'm having issues with releases too for the past couple of days, where navigating to https://deno.land/x/init would not show the latest release for many hours after the release. Also the releases are not showing up in the Recently Updated section anymore in my case.

**Comment by crowlKats** [comment] 2022-03-20 23:00
@SheetJSDev this could have been caused by GitHub's outage a few days ago. Would be great if you could create a new tag to see if that is indeed the case

**Comment by SheetJSDev** [comment] 2022-03-21 02:23
tagged [v0.18.4+deno](https://github.com/SheetJS/sheetjs/tree/v0.18.4+deno) about 10 minutes ago but the corresponding url 404s: https://deno.land/x/sheetjs@v0.18.4+deno

To be sure it's not a tag name issue, https://deno.land/x/sheetjs@v0.18.0+deno does work

**Comment by crowlKats** [comment] 2022-08-25 06:10
Closing as not the case anymore

**Closed by crowlKats** 2022-08-25 06:10 UTC
