### ISSUE TITLE
Module URL error: 502: Bad Gateway (DEPLOYMENT_FAILED)

### ISSUE THREAD

**Issue by srackham** [denoland/dotland#2033] opened 2022-02-28 02:37 UTC
Opening the root URLs of my published modules
https://deno.land/x/drake/
https://deno.land/x/rimu/
in multiple browsers generates the following browser error across all (previously working) versions:

    502: Bad Gateway (DEPLOYMENT_FAILED)
    The deployment failed while serving the request.

The individual module files open without error, for example:
https://deno.land/x/drake/mod.ts
https://deno.land/x/drake@v1.5.1/mod.ts

The modules can also be successfully downloaded using import statements, for example:

```typescript
    import * as rimu from "https://deno.land/x/rimu@11.2.0/mod.ts";
```

**Comment by crowlKats** [comment] 2022-02-28 02:41
Duplicate of #2031

**Closed by crowlKats** 2022-02-28 02:41 UTC
